name: Testing
"on":
  push: {}

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    env:
      SECRETS: '${{ toJson(secrets) }}'
    steps:
      - run: env
      - run: echo "$SECRETS" | jq
